version: '3.7'

services:
  web:
    build: ./backend
    container_name: champion-rotation-predictor-backend
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    environment:
      - DEBUG=1