version: '3.7'

services:

  backend:
    build: ./backend
    image: 'backend'
    container_name: champion-rotation-predictor-backend
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi
    volumes:
      - ./backend/app/database.db:/usr/src/app/app/database.db
    ports:
      - '5000:5000'
